dataset_general_params:
  dir_graph: "dataset/piccolo/graph"
  train_df: "dataset/piccolo/train.csv"
  field_id: "id"
  field_text: "text_cleaned"
  field_label: "label"
  train_ft: "dataset/piccolo/synthetic_dataset.csv"
  field_id_ft: "index"
  field_text_ft: "text_cleaned"
  field_label_ft: "label"

train_dataset_params:
  train_social_net: "dataset/piccolo/graph/social_network_train.edg"
  train_spatial_net: "dataset/piccolo/graph/spatial_network_train.edg"
  consider_content: True
  consider_rel: True
  consider_spat: False
  retrain: True
  fine_tuning_rel: True
  fine_tuning_edge_path: "/content/my_tuning.edg"
test_dataset_params:
  test_df: "dataset/piccolo/test.csv"
  test_social_net: "dataset/piccolo/graph/social_network_test.edg"
  test_spatial_net: "dataset/piccolo/graph/spatial_network_test.edg"
  consider_content: True
  consider_rel: True
  consider_spat: False

model_params:
  dir_models: "dataset/piccolo/models"
  epochs_rel: 25
  epochs_spat: 25
  mlp_batch_size: 64
  mlp_lr: 3e-1
  ne_dim_rel: 128
  ne_dim_spat: 128
  ne_technique_rel: "graphsage"
  ne_technique_spat: "graphsage"
  w2v_path: "dataset/piccolo/models/GoogleNews-vectors-negative300.bin"
  w2v_epochs: 15